# Generated by Django 4.2.4 on 2023-08-13 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_id_customuser_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user_id',
            new_name='username',
        ),
    ]
