# Generated by Django 4.2.4 on 2023-08-13 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_username_customuser_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='id',
            new_name='username',
        ),
    ]
