# Generated by Django 4.2.4 on 2023-08-13 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_id_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='win_streak',
        ),
    ]
